### ISSUE TITLE
Installation on macOS fails

### ISSUE THREAD

**Issue by MauriceKrause** [hypro/hypro#18] opened 2018-11-29 14:23 UTC
The output of `$ cmake ..` includes `-- Use included version of AnTLR.`
`$ make resources` fails with output:

```
Scanning dependencies of target antlr4cpp
[  8%] Creating directories for 'antlr4cpp'
[  8%] Performing download step (DIR copy) for 'antlr4cpp'
[  8%] No patch step for 'antlr4cpp'
[ 16%] No update step for 'antlr4cpp'
[ 25%] Performing configure step for 'antlr4cpp'
-- antlr4cpp configure command succeeded.  See also /Users/username/hypro/build/resources/antlr_build/src/antlr4cpp-stamp/antlr4cpp-configure-*.log
[ 25%] Performing build step for 'antlr4cpp'
CMake Error at /Users/username/hypro/build/resources/antlr_build/src/antlr4cpp-stamp/antlr4cpp-build-Release.cmake:16 (message):
  Command failed: 2

   '/Library/Developer/CommandLineTools/usr/bin/make'

  See also

    /Users/username/hypro/build/resources/antlr_build/src/antlr4cpp-stamp/antlr4cpp-build-*.log


make[3]: *** [resources/antlr_build/src/antlr4cpp-stamp/antlr4cpp-build] Error 1
make[2]: *** [src/resources/CMakeFiles/antlr4cpp.dir/all] Error 2
make[1]: *** [src/resources/CMakeFiles/resources.dir/rule] Error 2
make: *** [resources] Error 2
```

The file `/Users/username/hypro/build/resources/antlr_build/src/antlr4cpp-stamp/antlr4cpp-build-err.log` contains: `make[4]: *** No targets specified and no makefile found. Stop.`

**Comment by hypro** [comment] 2018-11-29 15:22
Thank you for reporting this, I assume you are trying to build the master branch, right? I will work on a fix for this asap.

**Comment by MauriceKrause** [comment] 2018-11-29 15:35
I'm using [this revision](https://github.com/smtrat/carl/commit/ace90eb5daad)
for CArl and [this one](https://github.com/hypro/hypro/commit/9a19fa931ade) for HyPro. But the problem also occurs building the master branch

**Comment by MauriceKrause** [comment] 2018-11-29 15:36
I'm using [this revision](https://github.com/smtrat/carl/commit/ace90eb5daad) for CArl and [this one](https://github.com/hypro/hypro/commit/9a19fa931ade) for HyPro. But the problem also occurs building the master branch

**Comment by modass** [comment] 2018-11-30 07:54
So I tried reproducing your problem with the given versions of CArL and HyPro, but on my machine I was not able to reproduce this. 

- Did it work before or is this your first attempt to build HyPro?
- Have you installed required libraries and packages for Antlr (some Java RE and uuid-dev)?
- Can you please provide the logs from the configure step as well?

**Comment by MauriceKrause** [comment] 2018-11-30 11:20
I've got the same setup and this is my first attempt to build HyPro.

I'm running OpenJDK Runtime Environment 18.9 (build 11.0.1+13) and ossp-uuid 1.6.2

`cmake ..` prints:

```
-- The CXX compiler identification is AppleClang 10.0.0.10001044
-- The C compiler identification is AppleClang 10.0.0.10001044
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Using clang on apple
-- Library GTest was not found.
-- Use system version of CArL
-- Download version of GTest
-- Use included version of AnTLR
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- Looking for BSD native UUID
-- Looking for libuuid
-- Looking for libuuid - found
-- not using cotire
-- linking dynamic
-- Exporting to cmake
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/username/hypro/build
```

**Comment by hypro** [comment] 2018-11-30 11:31
Okay, what do the logs of the antlr-configure step say? There should be files such as 

/Users/username/hypro/build/resources/antlr_build/src/antlr4cpp-stamp/antlr4cpp-configure-*.log

**Comment by MauriceKrause** [comment] 2018-11-30 12:37
`antlr4cpp-configure-err.log` contains:

```
CMake Deprecation Warning at CMakeLists.txt:29 (CMAKE_POLICY):
  The OLD behavior for policy CMP0054 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


CMake Deprecation Warning at CMakeLists.txt:30 (CMAKE_POLICY):
  The OLD behavior for policy CMP0045 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


CMake Deprecation Warning at CMakeLists.txt:31 (CMAKE_POLICY):
  The OLD behavior for policy CMP0042 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


CMake Deprecation Warning at CMakeLists.txt:36 (CMAKE_POLICY):
  The OLD behavior for policy CMP0059 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


CMake Deprecation Warning at CMakeLists.txt:37 (CMAKE_POLICY):
  The OLD behavior for policy CMP0054 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_SOURCE_DIR
```

And `antlr4cpp-configure-out.log` contains:

```
-- Building without demo. To enable demo build use: -DWITH_DEMO=True
-- The C compiler identification is AppleClang 10.0.0.10001044
-- The CXX compiler identification is AppleClang 10.0.0.10001044
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Output libraries to /Users/username/hypro/build/resources/antlr_build/src/antlr4cpp/dist
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/username/hypro/build/resources/antlr_build/src/antlr4cpp-build/UILD_TESTS=OFF
```

**Comment by hypro** [comment] 2018-11-30 13:58
Just to make sure: the file `/Users/username/hypro/build/resources/antlr_build/src/antlr4cpp-stamp/antlr4cpp-build-err.log` contains only one line stating `make[4]: *** No targets specified and no makefile found. Stop.`?

**Comment by MauriceKrause** [comment] 2018-11-30 14:24
That's absolutely correct

**Comment by hypro** [comment] 2018-11-30 14:31
Have you tried a newer version of HyPro yet? I guess the latest version which still allows to utilize c++14 is tagged "c++14", maybe this one works. TBH I cannot read much from those error logs, I assume there is no Makefile generated either, right?

Note that as long as you want to use c++14 you have to stay at the tagged commit and also use the latest commit on CArL's "master14" branch. Everything else will make use of c++17.

**Comment by MauriceKrause** [comment] 2018-11-30 15:11
### Building the master14 of carl and master **or** commit 9a19fa931ade8d15b5fa2bd8842fe626880fc2b2 of hypro both result in:
`/Users/username/hypro/build/Makefile` contains:

```
# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

<...>

#=============================================================================
# Target rules for targets named antlr4cpp

# Build rule for target.
antlr4cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 antlr4cpp
.PHONY : antlr4cpp

# fast build rule for target.
antlr4cpp/fast:
	$(MAKE) -f src/resources/CMakeFiles/antlr4cpp.dir/build.make src/resources/CMakeFiles/antlr4cpp.dir/build
.PHONY : antlr4cpp/fast

<...>

# Help Target
help:
<...>
	@echo "... antlr4cpp"
<...>
.PHONY : help
```

**Comment by MauriceKrause** [comment] 2018-11-30 15:11
Building the master14 of carl and master **or** commit 9a19fa931ade8d15b5fa2bd8842fe626880fc2b2 of hypro both result in:
`/Users/username/hypro/build/Makefile` contains:

```
# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

<...>

#=============================================================================
# Target rules for targets named antlr4cpp

# Build rule for target.
antlr4cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 antlr4cpp
.PHONY : antlr4cpp

# fast build rule for target.
antlr4cpp/fast:
	$(MAKE) -f src/resources/CMakeFiles/antlr4cpp.dir/build.make src/resources/CMakeFiles/antlr4cpp.dir/build
.PHONY : antlr4cpp/fast

<...>

# Help Target
help:
<...>
	@echo "... antlr4cpp"
<...>
.PHONY : help
```

**Comment by MauriceKrause** [comment] 2018-11-30 15:34
Right now I built the master of carl and master of hypro, getting the same error.

`/Users/username/hypro/build/resources/antlr_build/src/antlr4cpp-build/UILD_TESTS=OFF/Makefile`:

```
# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.13.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.13.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/username/hypro/build/resources/antlr_build/src/antlr4cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/username/hypro/build/resources/antlr_build/src/antlr4cpp-build/UILD_TESTS=OFF

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.13.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.13.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.13.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.13.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.13.1/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.13.1/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"dev\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.13.1/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.13.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/username/hypro/build/resources/antlr_build/src/antlr4cpp-build/UILD_TESTS=OFF/CMakeFiles /Users/username/hypro/build/resources/antlr_build/src/antlr4cpp-build/UILD_TESTS=OFF/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/username/hypro/build/resources/antlr_build/src/antlr4cpp-build/UILD_TESTS=OFF/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named make_lib_output_dir

# Build rule for target.
make_lib_output_dir: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 make_lib_output_dir
.PHONY : make_lib_output_dir

# fast build rule for target.
make_lib_output_dir/fast:
	$(MAKE) -f runtime/CMakeFiles/make_lib_output_dir.dir/build.make runtime/CMakeFiles/make_lib_output_dir.dir/build
.PHONY : make_lib_output_dir/fast

#=============================================================================
# Target rules for targets named antlr4_static

# Build rule for target.
antlr4_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 antlr4_static
.PHONY : antlr4_static

# fast build rule for target.
antlr4_static/fast:
	$(MAKE) -f runtime/CMakeFiles/antlr4_static.dir/build.make runtime/CMakeFiles/antlr4_static.dir/build
.PHONY : antlr4_static/fast

#=============================================================================
# Target rules for targets named antlr4_shared

# Build rule for target.
antlr4_shared: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 antlr4_shared
.PHONY : antlr4_shared

# fast build rule for target.
antlr4_shared/fast:
	$(MAKE) -f runtime/CMakeFiles/antlr4_shared.dir/build.make runtime/CMakeFiles/antlr4_shared.dir/build
.PHONY : antlr4_shared/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... make_lib_output_dir"
	@echo "... antlr4_static"
	@echo "... antlr4_shared"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system
```

There are also files `/Users/username/hypro/build/resources/antlr_build/src/antlr4cpp-build/UILD_TESTS=OFF/CMakeFiles/Makefile.cmake` and `/Users/username/hypro/build/resources/antlr_build/src/antlr4cpp-build/UILD_TESTS=OFF/CMakeFiles/Makefile2`

**Comment by MauriceKrause** [comment] 2018-11-30 16:00
On master of carl and master of hypro `cmake ..` prints:

```
<...>
-- Use included version of AnTLR
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
<...>
-- not using cotire
-- linking dynamic
-- Exporting to cmake
CMake Warning (dev) at cmake/hypromacros.cmake:41 (get_target_property):
  Policy CMP0045 is not set: Error on non-existent target in
  get_target_property.  Run "cmake --help-policy CMP0045" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  get_target_property() called with non-existent target "lib_carl".
Call Stack (most recent call first):
  cmake/export.cmake:31 (export_target)
  CMakeLists.txt:203 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Unknown type TYPE-NOTFOUND
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/username/hypro/build
```

**Comment by MauriceKrause** [comment] 2018-11-30 16:02
Using master of carl. On master of hypro `cmake ..` prints:

```
<...>
-- Use included version of AnTLR
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
<...>
-- not using cotire
-- linking dynamic
-- Exporting to cmake
CMake Warning (dev) at cmake/hypromacros.cmake:41 (get_target_property):
  Policy CMP0045 is not set: Error on non-existent target in
  get_target_property.  Run "cmake --help-policy CMP0045" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  get_target_property() called with non-existent target "lib_carl".
Call Stack (most recent call first):
  cmake/export.cmake:31 (export_target)
  CMakeLists.txt:203 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Unknown type TYPE-NOTFOUND
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/username/hypro/build
```

**Comment by hypro** [comment] 2018-11-30 23:29
Okay, and does the current master (both, carl and hypro) build on your machine?

**Comment by MauriceKrause** [comment] 2018-12-01 17:15
Master of carl build without problems. Master of hypro doesn't.

- cmake prints warning (see last comment)
- make resources still fails at the same point (see penultimate comment)
- makefile as in penultimate comment

**Comment by modass** [comment] 2018-12-03 09:18
I have updated the master branch of HyPro and merged it with the dev-branch "alpha". Currently the CI is still compiling, but previous runs hint that both, carl master and hypro master are now compatible again.

Can you please update hypro to the current version on the master branch and try again? I will also try again to reproduce your error on my laptop here.

**Comment by MauriceKrause** [comment] 2018-12-03 13:13
`cmake ..` still prints the warning `-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)`.

Full output:
```
-- The CXX compiler identification is AppleClang 10.0.0.10001044
-- The C compiler identification is AppleClang 10.0.0.10001044
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- clang 10.0.0.10001044 does not ship the proper libc++.
-- Auto-detected brew-installed llvm version
-- Using clang on apple
-- Library GTest was not found.
-- Use system version of CArL
-- Download version of GTest
-- glpk include dir: /Users/username/hypro/build/resources/src/glpk_download/include
-- Use included version of AnTLR
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- Looking for BSD native UUID
-- Looking for libuuid
-- Looking for libuuid - found
-- not using cotire
-- linking dynamic
-- Exporting to cmake
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/username/hypro/build
```

`make resources` still fails at `build step for 'antlr4cpp'` because of missing makefile

**Comment by MauriceKrause** [comment] 2018-12-03 13:17
`cmake ..` still prints can't find PkgConfig (`-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)`).

Full output:
```
-- The CXX compiler identification is AppleClang 10.0.0.10001044
-- The C compiler identification is AppleClang 10.0.0.10001044
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- clang 10.0.0.10001044 does not ship the proper libc++.
-- Auto-detected brew-installed llvm version
-- Using clang on apple
-- Library GTest was not found.
-- Use system version of CArL
-- Download version of GTest
-- glpk include dir: /Users/username/hypro/build/resources/src/glpk_download/include
-- Use included version of AnTLR
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- Looking for BSD native UUID
-- Looking for libuuid
-- Looking for libuuid - found
-- not using cotire
-- linking dynamic
-- Exporting to cmake
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/username/hypro/build
```

`make resources` still fails at `build step for 'antlr4cpp'` because of missing makefile

**Comment by modass** [comment] 2018-12-03 13:40
Ah okay. Can you please try installing pkg-config via homebrew and then try again?

**Comment by MauriceKrause** [comment] 2018-12-03 13:44
This helped for `cmake ..` (`-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2")`).

But `make resources` still fails at `build step for 'antlr4cpp'` because of missing makefile.

**Comment by modass** [comment] 2018-12-03 13:47
Okay. Just to make sure there is no cache which keeps us from getting it running: could you just remove the content of your build-folder and try again, i.e. run
`hypro/build$ rm -rf *
hypro/build$ cmake .. && make resources`

**Comment by MauriceKrause** [comment] 2018-12-03 13:51
Still the same failure with the same output in `/Users/username/hypro/build/resources/antlr_build/src/antlr4cpp-stamp/antlr4cpp-build-err.log` (No targets specified and no makefile found)

**Comment by modass** [comment] 2018-12-03 13:54
Weird. I'll think of something and keep you updated.

**Comment by MauriceKrause** [comment] 2018-12-03 15:39
Yes, I'm running
```
$ git clone https://github.com/hypro/hypro && cd hypro
$ mkdir build && cd build && cmake ..
$ make resources
```

**Comment by MauriceKrause** [comment] 2018-12-03 15:53
Just to make sure, I'm pointing out again, that `/Users/username/hypro/build/resources/antlr_build/src/antlr4cpp-stamp/antlr4cpp-configure-err.log` contains

```
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_SOURCE_DIR
```

Is this okay?

**Comment by MauriceKrause** [comment] 2018-12-03 15:54
Just to make sure, I'm pointing out again, that `/Users/username/hypro/build/resources/antlr_build/src/antlr4cpp-stamp/antlr4cpp-configure-err.log` contains

```
<...>
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_SOURCE_DIR
```

Is this okay?

**Comment by modass** [comment] 2018-12-03 15:55
Hm, at some point this also made me think. I'll have a look!

**Comment by modass** [comment] 2018-12-03 15:58
This is definitely something I should fix, but I have a similar output in my err.log as well.

**Comment by MauriceKrause** [comment] 2018-12-03 16:20
I'm running:
```
gmp: stable 6.1.2
boost: stable 1.68.0 optional dependency icu4c NOT installed
eigen: stable 3.3.5
cgal: stable 4.13 optional dependency qt NOT installed
gsl: stable 2.5
java: 11.0.1,13
xerces-c: stable 3.2.2
ossp-uuid: stable 1.6.2
pkg-config: stable 0.29.2
```

Do you use other versions?

**Comment by MauriceKrause** [comment] 2018-12-03 16:24
I'm running:
```
gmp: stable 6.1.2
boost: stable 1.68.0 optional dependency icu4c NOT installed
eigen: stable 3.3.5
cgal: stable 4.13 optional dependency qt NOT installed
gsl: stable 2.5
java: 11.0.1,13
xerces-c: stable 3.2.2
ossp-uuid: stable 1.6.2
```

**Comment by modass** [comment] 2018-12-04 08:20
Apparently uuid-dev is already part of OSX, so no need to have it separately (i.e. you can remove ossp-uuid). The other packages you mentioned such as cgal, gsl and xerces-c are not required. 

I assume you installed boost yourself using homebrew as well as eigen3?

**Comment by MauriceKrause** [comment] 2018-12-04 14:39
> Apparently uuid-dev is already part of OSX

I read that too, but upon trying to install Hypro, I checked if a manual installation of `ossp-uuid` would help. It doesn't. Such as a manual installation of `antlr` or `antlr4-cpp-runtime` does not help.

Removing `ossp-uuid` and all other unnecessary packages also doesn't help installing hypro.

> I assume you installed boost yourself using homebrew as well as eigen3?

This is correct, also for `gmp`.

**Comment by MauriceKrause** [comment] 2018-12-04 14:53
To reproduce my problem, have you tried to also remove carl completely and start with a fresh version of it, before installing hypro?

**Comment by modass** [comment] 2018-12-04 14:57
Wait, you install carl? So usually it suffices to build it, i.e. clone carl, create a build directory, execute "cmake .." from said directory and then invoke make.

Same process also applies to hypro.

Yes, I've deleted the contents of my build folder for carl and for hypro and started with the current master branch state. I will do it again, just to make sure

**Comment by MauriceKrause** [comment] 2018-12-04 15:04
I meant built.

I use:
```
           username$ git clone https://github.com/smtrat/carl && cd carl
      username/carl$ mkdir build && cd build && cmake ..
username/carl/build$ make

            username$ git clone https://github.com/hypro/hypro && cd hypro
      username/hypro$ mkdir build && cd build && cmake ..
username/hypro/build$ make resources
username/hypro/build$ make hypro
```

**Comment by modass** [comment] 2018-12-04 15:23
Jeah, that looks correct - I will try a complete, fresh copy and keep you updated.

**Comment by modass** [comment] 2018-12-05 08:14
On my Mac with a freshly pulled carl and hypro I could build hypro. I will now try to set up a clean VM and only install homebrew, java and llvm (from homebrew) and then try to reproduce your errors.

**Comment by modass** [comment] 2019-01-07 13:33
We have found a potential problem and fixed it in the current state of the alpha-branch. Can you please try this and tell me, whether that solves your problem?

**Comment by MauriceKrause** [comment] 2019-01-08 14:49
Commit `ad01f36f2af526b7d0481a7e775bf130d138aa82` works for me. Many thanks.

**Closed** 2019-01-08 15:01 UTC
